### ISSUE TITLE
Linking fails on macOS

### ISSUE THREAD

**Issue by jquorning** [mosteo/rsfile#2]
Linking fails macOS [1] because of unknown option: --gc-sections. The corresponding option is -dead_strip.

[1] https://alire-crate-ci.ada.dev/status/rs/rsfile/1.0.0/macos/darwin-20.6.0/gnat=11.2.4/rsfile-1.0.0.yaml.log

**Comment by mosteo** [comment]
It'll be easier to just remove that --gc-sections. I didn't use it in consciously at all. Thanks!

**Comment by mosteo** [comment]
Published via https://github.com/alire-project/alire-index/pull/592
